version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - blizzz
  - juliushaertl
  ignore:
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.1
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.13.2
    - 7.13.6
    - 7.13.7
  - dependency-name: "@nextcloud/vue"
    versions:
    - 3.5.5
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
